# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(611, 447)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget.setStyleSheet("background: qlineargradient(x1: 0,\n"
"    y1: 0,\n"
"    x2: 1,\n"
"    y2: 0,\n"
"    stop: 0 rgba(77, 173, 162, 255),\n"
"    stop: 1 rgba(94, 192, 182, 255)\n"
");\n"
"")
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(430, 16777215))
        self.frame_2.setStyleSheet("background-color: rgba(250, 250, 240); /* Slight transparency */\n"
"\n"
"\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_1 = QtWidgets.QLabel(self.frame_2)
        self.lbl_1.setStyleSheet("/*background-color: rgb(38, 166, 154);*/\n"
"color: rgb(38, 166, 154);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lbl_1.setObjectName("lbl_1")
        self.verticalLayout.addWidget(self.lbl_1)
        self.treeWidget = QtWidgets.QTreeWidget(self.frame_2)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.treeWidget)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_1.setText(_translate("MainWindow", "View Tree Data"))
