# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Login(object):
    def setupUi(self, Dialog_Login):
        Dialog_Login.setObjectName("Dialog_Login")
        Dialog_Login.resize(340, 380)
        Dialog_Login.setMinimumSize(QtCore.QSize(340, 380))
        Dialog_Login.setMaximumSize(QtCore.QSize(340, 380))
        Dialog_Login.setStyleSheet("/*background-color: #8B6E4E;*/\n"
"background-color:qlineargradient(spread:pad, x1:0.58, y1:0.085, x2:0.778, y2:1, stop:0 rgba(139, 94, 60, 255), stop:1 rgba(255, 255, 255, 255))\n"
"")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Dialog_Login)
        self.verticalLayout_5.setContentsMargins(4, 0, 2, 5)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_5 = QtWidgets.QFrame(Dialog_Login)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_5.setStyleSheet("background-color:transparent")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_courseshub = QtWidgets.QLabel(self.frame_5)
        self.label_courseshub.setStyleSheet("QLabel{\n"
"    color: #FFFFFF;  /* Clean white text */\n"
"    font:  bold 20pt \"Californian FB\";\n"
"    text-shadow: 0 0 10px rgba(255, 255, 255, 0.7); /* Subtle glow effect */\n"
"    letter-spacing: 2px; /* Spacing for a cleaner and airy effect */\n"
"\n"
"}")
        self.label_courseshub.setObjectName("label_courseshub")
        self.verticalLayout_6.addWidget(self.label_courseshub, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.frame_5, 0, QtCore.Qt.AlignTop)
        self.frame_4 = QtWidgets.QFrame(Dialog_Login)
        self.frame_4.setStyleSheet("QFrame {\n"
"    background-color: #F5F5DC;\n"
"    border-top-left-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white; /* Ensure background is white */\n"
"    border: 1px solid #ccc;  /* Set a light border for QLineEdit */\n"
"    border-radius: 10px;       /* Optional: rounded edges for QLineEdit */\n"
"    padding: 5px;             /* Optional: add some padding */\n"
"}\n"
"\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_login = QtWidgets.QLabel(self.frame_2)
        self.label_login.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_login.setStyleSheet("QLabel {\n"
"    font: bold 24px;               /* Bold and large text for emphasis */\n"
"    color: rgb(84, 42, 0);                  /* White text to contrast against the blue background */\n"
"    background-color: transparent; /* No background for the label */\n"
"    text-align: center;            /* Center-align the text horizontally */\n"
"    border: none;                  /* No border */\n"
"}")
        self.label_login.setObjectName("label_login")
        self.verticalLayout_4.addWidget(self.label_login)
        self.verticalLayout_3.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter)
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setStyleSheet("background-color:transparent;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(40, -1, 40, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txt_username = QtWidgets.QLineEdit(self.frame)
        self.txt_username.setStyleSheet("")
        self.txt_username.setObjectName("txt_username")
        self.gridLayout_2.addWidget(self.txt_username, 0, 0, 1, 1)
        self.txt_password = QtWidgets.QLineEdit(self.frame)
        self.txt_password.setObjectName("txt_password")
        self.gridLayout_2.addWidget(self.txt_password, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.lbl_loginerror = QtWidgets.QLabel(self.frame_3)
        self.lbl_loginerror.setStyleSheet("padding-left: 40px;\n"
"color:red;")
        self.lbl_loginerror.setText("")
        self.lbl_loginerror.setObjectName("lbl_loginerror")
        self.verticalLayout_2.addWidget(self.lbl_loginerror)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout.setContentsMargins(110, -1, 110, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_login = QtWidgets.QPushButton(self.frame_6)
        self.btn_login.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_login.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"color:white;\n"
"font: 18px;\n"
"background-color: #8B6E4E;\n"
"}\n"
"/* Hover effect */\n"
"QPushButton:hover {\n"
"    background-color: #8B5E3C;  /* Lighter shade for hover */\n"
"}\n"
"\n"
"/* Clicked (pressed) effect */\n"
"QPushButton:pressed {\n"
"    background-color: #6A3E26;  /* Darker shade for click effect */\n"
"}")
        self.btn_login.setObjectName("btn_login")
        self.horizontalLayout.addWidget(self.btn_login)
        self.verticalLayout_2.addWidget(self.frame_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.verticalLayout_5.addWidget(self.frame_4)

        self.retranslateUi(Dialog_Login)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Login)

    def retranslateUi(self, Dialog_Login):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Login.setWindowTitle(_translate("Dialog_Login", "Dialog"))
        self.label_courseshub.setText(_translate("Dialog_Login", "Courses Hub"))
        self.label_login.setText(_translate("Dialog_Login", "Login"))
        self.btn_login.setText(_translate("Dialog_Login", "Login"))
