# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(420, 375)
        LoginWindow.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label.setStyleSheet("font: bold 18pt \"Calibre\"; color:rgb(231, 231, 231)")
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lbl_login_email = QtWidgets.QLabel(self.frame_2)
        self.lbl_login_email.setGeometry(QtCore.QRect(40, 50, 61, 21))
        self.lbl_login_email.setStyleSheet("font: bold 16px; color:rgb(204, 0, 0)")
        self.lbl_login_email.setObjectName("lbl_login_email")
        self.txt_login_email = QtWidgets.QLineEdit(self.frame_2)
        self.txt_login_email.setGeometry(QtCore.QRect(150, 50, 181, 20))
        self.txt_login_email.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.txt_login_email.setPlaceholderText("")
        self.txt_login_email.setObjectName("txt_login_email")
        self.lbl_login_pass = QtWidgets.QLabel(self.frame_2)
        self.lbl_login_pass.setGeometry(QtCore.QRect(40, 80, 101, 21))
        self.lbl_login_pass.setStyleSheet("font: bold 16px; color:rgb(204, 0, 0)")
        self.lbl_login_pass.setObjectName("lbl_login_pass")
        self.txt_login_pass = QtWidgets.QLineEdit(self.frame_2)
        self.txt_login_pass.setGeometry(QtCore.QRect(150, 80, 181, 20))
        self.txt_login_pass.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.txt_login_pass.setPlaceholderText("")
        self.txt_login_pass.setObjectName("txt_login_pass")
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_login_signin = QtWidgets.QPushButton(self.frame_4)
        self.btn_login_signin.setMaximumSize(QtCore.QSize(60, 22))
        self.btn_login_signin.setStyleSheet("font: 14px;\n"
"background-color: rgb(235, 235, 235);")
        self.btn_login_signin.setObjectName("btn_login_signin")
        self.horizontalLayout.addWidget(self.btn_login_signin)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(110, 10, 114, 16))
        self.label_2.setMaximumSize(QtCore.QSize(130, 20))
        self.label_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.btn_login_register = QtWidgets.QPushButton(self.frame_5)
        self.btn_login_register.setGeometry(QtCore.QRect(230, 10, 40, 16))
        self.btn_login_register.setMaximumSize(QtCore.QSize(50, 20))
        self.btn_login_register.setBaseSize(QtCore.QSize(0, 0))
        self.btn_login_register.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    text-decoration: underline;\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: lightblue;\n"
"}")
        self.btn_login_register.setObjectName("btn_login_register")
        self.verticalLayout_3.addWidget(self.frame_5)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 21))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.label.setText(_translate("LoginWindow", "Login"))
        self.lbl_login_email.setText(_translate("LoginWindow", "Email"))
        self.lbl_login_pass.setText(_translate("LoginWindow", "Password"))
        self.btn_login_signin.setText(_translate("LoginWindow", "Sign In"))
        self.label_2.setText(_translate("LoginWindow", "Don\'t Have an account?"))
        self.btn_login_register.setText(_translate("LoginWindow", "Register"))
