# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app11_listwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(476, 459)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(60, 50, 181, 221))
        self.listWidget.setObjectName("listWidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(290, 60, 79, 201))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_add = QtWidgets.QPushButton(self.widget)
        self.btn_add.setObjectName("btn_add")
        self.verticalLayout.addWidget(self.btn_add)
        self.btn_remove = QtWidgets.QPushButton(self.widget)
        self.btn_remove.setObjectName("btn_remove")
        self.verticalLayout.addWidget(self.btn_remove)
        self.btn_edit = QtWidgets.QPushButton(self.widget)
        self.btn_edit.setObjectName("btn_edit")
        self.verticalLayout.addWidget(self.btn_edit)
        self.btn_up = QtWidgets.QPushButton(self.widget)
        self.btn_up.setObjectName("btn_up")
        self.verticalLayout.addWidget(self.btn_up)
        self.btn_down = QtWidgets.QPushButton(self.widget)
        self.btn_down.setObjectName("btn_down")
        self.verticalLayout.addWidget(self.btn_down)
        self.btn_sort = QtWidgets.QPushButton(self.widget)
        self.btn_sort.setObjectName("btn_sort")
        self.verticalLayout.addWidget(self.btn_sort)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.btn_exit = QtWidgets.QPushButton(self.widget)
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout_2.addWidget(self.btn_exit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 476, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_add.setText(_translate("MainWindow", "Add"))
        self.btn_remove.setText(_translate("MainWindow", "Remove"))
        self.btn_edit.setText(_translate("MainWindow", "Edit"))
        self.btn_up.setText(_translate("MainWindow", "Move Up"))
        self.btn_down.setText(_translate("MainWindow", "Move Down"))
        self.btn_sort.setText(_translate("MainWindow", "Sort"))
        self.btn_exit.setText(_translate("MainWindow", "Exit"))
