# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app4_calc_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""
code used to convert:  pyuic5 app4_calc_designer.ui -o app4_converted_calc.py
"""

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_num1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_num1.setGeometry(QtCore.QRect(90, 60, 47, 13))
        self.lbl_num1.setObjectName("lbl_num1")
        self.lbl_num2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_num2.setGeometry(QtCore.QRect(90, 110, 47, 13))
        self.lbl_num2.setObjectName("lbl_num2")
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(180, 270, 101, 71))
        self.lbl_result.setObjectName("lbl_result")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(90, 190, 51, 41))
        self.btn_add.setObjectName("btn_add")
        self.btn_sub = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sub.setGeometry(QtCore.QRect(190, 190, 51, 41))
        self.btn_sub.setObjectName("btn_sub")
        self.btn_mul = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mul.setGeometry(QtCore.QRect(290, 190, 51, 41))
        self.btn_mul.setObjectName("btn_mul")
        self.btn_div = QtWidgets.QPushButton(self.centralwidget)
        self.btn_div.setGeometry(QtCore.QRect(390, 190, 51, 41))
        self.btn_div.setObjectName("btn_div")
        self.txt_num1 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_num1.setGeometry(QtCore.QRect(190, 50, 104, 31))
        self.txt_num1.setObjectName("txt_num1")
        self.txt_num2 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_num2.setGeometry(QtCore.QRect(190, 100, 104, 31))
        self.txt_num2.setObjectName("txt_num2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 491, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_num1.setText(_translate("MainWindow", "Number 1"))
        self.lbl_num2.setText(_translate("MainWindow", "Number 2"))
        self.lbl_result.setText(_translate("MainWindow", "Result:"))
        self.btn_add.setText(_translate("MainWindow", "+"))
        self.btn_sub.setText(_translate("MainWindow", "-"))
        self.btn_mul.setText(_translate("MainWindow", "*"))
        self.btn_div.setText(_translate("MainWindow", "/"))
