# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app10_dates.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(524, 336)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(10, 540, 701, 20))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.btn_startCurrent = QtWidgets.QPushButton(self.centralwidget)
        self.btn_startCurrent.setGeometry(QtCore.QRect(290, 140, 161, 23))
        self.btn_startCurrent.setObjectName("btn_startCurrent")
        self.lbl_startCurrent = QtWidgets.QLabel(self.centralwidget)
        self.lbl_startCurrent.setGeometry(QtCore.QRect(290, 190, 151, 61))
        self.lbl_startCurrent.setText("")
        self.lbl_startCurrent.setObjectName("lbl_startCurrent")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(120, 40, 261, 51))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.D_start = QtWidgets.QDateEdit(self.splitter)
        self.D_start.setCalendarPopup(True)
        self.D_start.setDate(QtCore.QDate(2024, 11, 1))
        self.D_start.setObjectName("D_start")
        self.D_end = QtWidgets.QDateEdit(self.splitter)
        self.D_end.setCalendarPopup(True)
        self.D_end.setDate(QtCore.QDate(2024, 11, 30))
        self.D_end.setObjectName("D_end")
        self.lbl_startEnd = QtWidgets.QLabel(self.centralwidget)
        self.lbl_startEnd.setGeometry(QtCore.QRect(70, 190, 151, 61))
        self.lbl_startEnd.setText("")
        self.lbl_startEnd.setScaledContents(False)
        self.lbl_startEnd.setObjectName("lbl_startEnd")
        self.btn_startEnd = QtWidgets.QPushButton(self.centralwidget)
        self.btn_startEnd.setGeometry(QtCore.QRect(70, 140, 161, 23))
        self.btn_startEnd.setObjectName("btn_startEnd")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 524, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_startCurrent.setText(_translate("MainWindow", "get start to current date days"))
        self.btn_startEnd.setText(_translate("MainWindow", "get start to end days"))
